### ISSUE TITLE
ds.presence.subscribe() results in ACK_TIMEOUT if called after logging in

### ISSUE THREAD

**Issue by vovayartsev** [deepstreamIO/deepstream.io-client-js#408]
Please try out the following code:

```
const deepstream = require('deepstream.io-client-js');
const creds = {type: "open"}

const BRANCH = "GOOD" // or "BAD"

const client = deepstream('wss://154.deepstreamhub.com?apiKey=a94252fb-2bdc-4b16-ae3b-fa7c1ba8d507')

function setupSubscription() {
	client.presence.subscribe((username, online) => {
		console.log("Presence: ", username, online)
	})
}

client.login(creds, function() {
	if (BRANCH == "BAD") {
		console.log("This will throw ACK_TIMEOUT in ~2 seconds and crash")
		setupSubscription()
	}
})

if (BRANCH == "GOOD") {
	console.log("This will work fine:")
	setupSubscription()
}
```

**Expected:**
"GOOD" and "BAD" branch should behave equally well: they should print presence events on the console, e.g.:

```
Presence:  6a4dd0c7-d70e-460e-9002-322ba2a16fc1 false
Presence:  ae41ee50-c619-4113-b768-e34f59c2d595 true
```

**Actual:**
In "BAD" branch, presence events don't appear, the app crashes in ~3 seconds.

```
Error: ACK_TIMEOUT: No ACK message received in time for S (U)
    at Client._$onError (.../node_modules/deepstream.io-client-js/dist/lib/client.js:204:11)
    at AckTimeoutRegistry._onTimeout .../node_modules/deepstream.io-client-js/dist/lib/utils/ack-timeout-registry.js:122:18)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Environment**

MacOS 10.12, NodeJS v8.5.0, deepstream.io-client-js v2.3.0

**Thoughts**

1. This can be reproduced regardless of Deepstream server (latest docker image or deepstreamHub)
2. This can be reproduced even if I move the `setupSubscription()` call from the callback and use async/await instead.

**Comment by yasserf** [comment]
Hey thanks for raising, this is certainly something we'll fix ASAP.

You can do do client.on('error', () => {}) to capture all error events and not result in an app crash. Ack timeouts themselves are not actually error states, we will be reducing those going forward to just emit an event for curious developer purposes

**Comment by IvanCaceres** [comment]
i can confirm that this issue happens when subscribing to .presence after going through .login()

**Comment by AlexBHarley** [comment]
This is fixed in v4

**Comment by teckays** [comment]
@AlexBHarley  Any plans to publish the v4-beta version to NPM?

**Comment by teckays** [comment]
Also, I've tried v4, this is still not working! Please see: https://github.com/deepstreamIO/deepstream.io-client-js/issues/457

**Comment by yasserf** [comment]
Thanks for raising. We are currently trying to get our enterprise features working with V4 before making another RC, but we'll look into this as soon as possible. Thanks!

**Comment by yasserf** [comment]
Closing due to inactivity and rewrite
